src/Entity/Icon.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IconRepository")
 * @ORM\Table(name="Icon")
 */
class Icon
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="IconID", type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $icon_small;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $icon_medium;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $icon_large;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Member", mappedBy="icon", cascade={"persist", "remove"})
     */
    private $member;

    public function getId()
    {
        return $this->id;
    }

    public function getIconSmall(): ?string
    {
        return $this->icon_small;
    }

    public function setIconSmall(string $icon_small): self
    {
        $this->icon_small = $icon_small;

        return $this;
    }

    public function getIconMedium(): ?string
    {
        return $this->icon_medium;
    }

    public function setIconMedium(string $icon_medium): self
    {
        $this->icon_medium = $icon_medium;

        return $this;
    }

    public function getIconLarge(): ?string
    {
        return $this->icon_large;
    }

    public function setIconLarge(string $icon_large): self
    {
        $this->icon_large = $icon_large;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(Member $member): self
    {
        $this->member = $member;

        // set the owning side of the relation if necessary
        if ($this !== $member->getIcon()) {
            $member->setIcon($this);
        }

        return $this;
    }
}

src/Entity/Member.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MemberRepository")
 * @ORM\Table(name="Member")
 */
class Member implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="MemberID", type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="PersonalContacts", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity="PersonalCategories", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="PersonalBlockeds", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $blockeds;

    /**
     * @ORM\ManyToMany(targetEntity="Settings")
     * @ORM\JoinTable(name="Personal_Settings",
     *     joinColumns={@ORM\JoinColumn(name="MemberID", referencedColumnName="MemberID")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="SettingsID", referencedColumnName="SettingsID")})
     */
    private $settings;

    /**
     * @ORM\OneToMany(targetEntity="PersonalLabels", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $labels;

    /**
     * @ORM\OneToMany(targetEntity="PersonalDefaultLabels", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $defaultLabels;

    /**
     * @ORM\ManyToMany(targetEntity="Theme", inversedBy="members")
     * @ORM\JoinTable(name="Personal_Themes",
     *     joinColumns={@ORM\JoinColumn(name="MemberID", referencedColumnName="MemberID")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="ThemeID", referencedColumnName="ThemeID")})
     */
    private $theme;

    /**
     * @ORM\OneToMany(targetEntity="ReceivedEmails", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $receivedEmails;

    /**
     * @ORM\OneToMany(targetEntity="SentEmails", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $sentEmails;

    /**
     * @ORM\OneToOne(targetEntity="Icon", inversedBy="member", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="IconID", referencedColumnName="IconID", nullable=true)
     */
    private $icon;

    /**
     * @ORM\Column(type="datetime", options={"default":"(now() at TIME ZONE 'utc')"})
     */
    private $last_active;

    public function __construct()
    {
        $this->contacts       = new ArrayCollection();
        $this->categories     = new ArrayCollection();
        $this->blockeds       = new ArrayCollection();
        $this->settings       = new ArrayCollection();
        $this->labels         = new ArrayCollection();
        $this->defaultLabels  = new ArrayCollection();
        $this->theme          = new ArrayCollection();
        $this->receivedEmails = new ArrayCollection();
        $this->sentEmails     = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?string
    {
        return $this->birthday;
    }

    public function setBirthday(?string $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection|PersonalContacts[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(PersonalContacts $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setMember($this);
        }

        return $this;
    }

    public function removePersonalContact(PersonalContacts $contact): self
    {
        if ($this->contacts->contains($contact)) {
            $this->contacts->removeElement($contact);
            // set the owning side to null (unless already changed)
            if ($contact->getMember() === $this) {
                $contact->setMember(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PersonalCategories[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(PersonalCategories $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setMember($this);
        }

        return $this;
    }

    public function removeCategory(PersonalCategories $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            // set the owning side to null (unless already changed)
            if ($category->getMember() === $this) {
                $category->setMember(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PersonalBlockeds[]
     */
    public function getBlockeds(): Collection
    {
        return $this->blockeds;
    }

    public function addBlocked(PersonalBlockeds $blocked): self
    {
        if (!$this->blockeds->contains($blocked)) {
            $this->blockeds[] = $blocked;
            $blocked->setMember($this);
        }

        return $this;
    }

    public function removeBlocked(PersonalBlockeds $blocked): self
    {
        if ($this->blockeds->contains($blocked)) {
            $this->blockeds->removeElement($blocked);
            // set the owning side to null (unless already changed)
            if ($blocked->getMember() === $this) {
                $blocked->setMember(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Settings[]
     */
    public function getSettings(): Collection
    {
        return $this->settings;
    }

    public function addSettings(Settings $settings): self
    {
        if (!$this->settings->contains($settings)) {
            $this->settings[] = $settings;
        }

        return $this;
    }

    public function removeSettings(Settings $settings): self
    {
        if ($this->settings->contains($settings)) {
            $this->settings->removeElement($settings);
        }

        return $this;
    }

    /**
     * @return Collection|PersonalLabels[]
     */
    public function getLabels(): Collection
    {
        return $this->labels;
    }

    public function addLabel(PersonalLabels $label): self
    {
        if (!$this->labels->contains($label)) {
            $this->labels[] = $label;
            $label->setMember($this);
        }

        return $this;
    }

    public function removeLabel(PersonalLabels $label): self
    {
        if ($this->labels->contains($label)) {
            $this->labels->removeElement($label);
            // set the owning side to null (unless already changed)
            if ($label->getMember() === $this) {
                $label->setMember(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PersonalDefaultLabels[]
     */
    public function getDefaultLabels(): Collection
    {
        return $this->defaultLabels;
    }

src/Controller/MemberController.php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\VarDumper\Dump;

use App\Entity\Member;
use App\Entity\PersonalBlockeds;
use App\Entity\PersonalContacts;

use App\Service\MemberInterface;

class MemberController extends AbstractController
{
    private $member;

    private function getMember(): ?Member
    {
        if (!isset($this->member)) {
            $this->member = $this->get('security.token_storage')
                                 ->getToken()
                                 ->getUser();
        }

        return $this->member;
    }

    /**
     * @Route("/member/details", name="member_details")
     * @Method({ "POST" })
     */
    public function getDetails(MemberInterface $interface): object
    {
        $member         = $this->getMember();
        $filteredMember = $interface->getMember($member->getId());
        return new JsonResponse($filteredMember);
    }

    /**
     * @Route("/member/blocked", name="member_blockeds")
     * @Method({ "POST" })
     */
    public function getBlocked(MemberInterface $interface): object
    {
        $member   = $this->getMember();
        $blockeds = $interface->getBlocked($member->getId());
        return new JsonResponse($blockeds);
    }

    /**
     * @Route("/member/contacts", name="member_contacts")
     * @Method({ "POST" })
     */
    public function getContacts(MemberInterface $interface): object
    {
        $member   = $this->getMember();
        $contacts = $interface->getContacts($member->getId());
        return new JsonResponse($contacts);
    }
}

templates/member/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if member is not null %}
        {{ member.info['username'] }}
    {% else %}
        Guesterino!
    {% endif %}
{% endblock %}

{% block body %}
{% if member is null %}
    <h2>Hello, Guest!</h2>
{% else %}
    <h2>Hello, {{ member.info['name']['full'] }}!</h2>
    <span><img src="{{ asset(member.data.icon.iconLarge, 'icons') }}" alt=""></span>
    <span><img src="{{ asset(member.data.icon.iconMedium, 'icons') }}" alt=""></span>
    <span><img src="{{ asset(member.data.icon.iconSmall, 'icons') }}" alt=""></span>
    <h2>{{ member.info['username'] }}'s</h2>
    <p>Received Emails</p>
    <table>
        <thead>
            <th>Important</th>
            <th>Starred</th>
            <th>Subject</th>
            <th>Body</th>
            <th>Author</th>
            <th>Time</th>
            <th>Category</th>
            <th>Labels</th>
        </thead>
        <tbody>
            {% for received in member.data['emails']['received'] %}
                {% if received.category.visibility %}
                <tr>
                    <td>
                        <input type="checkbox"
                            {% if received.important == 1 %}
                                checked
                            {% endif %}>
                    </td>
                    <td>
                        <input type="checkbox"
                            {% if received.starred == 1 %}
                                checked
                            {% endif %}>
                    </td>
                    <td>{{ received.email.subject }}</td>
                    <td>{{ received.email.body }}</td>
                    <td>{{ received.email.member.username }}</td>
                    <td>{{ received.email.timeSent|date('D M-Y') }}</td>
                    <td>{{ received.category.category.name }}</td>
                    <td>
                        {% for label in received.labels %}
                            {% if label.labels is not null %}
                                <span>{{ label.labels.label.name }}</span>
                            {% endif %}
                            {% if label.defaultLabels is not null %}
                                <span>{{ label.defaultLabels.label.name }}</span>
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <br>
    <p>Sent Emails</p>
    <table>
        <thead>
            <th>Important</th>
            <th>Starred</th>
            <th>Subject</th>
            <th>Body</th>
            <th>Author</th>
            <th>Time</th>
            <th>Category</th>
            <th>Labels</th>
        </thead>
        <tbody>
            {% for sent in member.data['emails']['sent'] %}
                {% if sent.category.visibility %}
                <tr>
                    <td>
                        <input type="checkbox"
                            {% if sent.important == 1 %}
                                checked
                            {% endif %}>
                    </td>
                    <td>
                        <input type="checkbox"
                            {% if sent.starred == 1 %}
                                checked
                            {% endif %}>
                    </td>
                    <td>{{ sent.email.subject }}</td>
                    <td>{{ sent.email.body }}</td>
                    <td>{{ sent.email.member.username }}</td>
                    <td>{{ sent.email.timeSent|date('D M-Y') }}</td>
                    <td>{{ sent.category.category.name }}</td>
                    <td>
                        {% for label in sent.labels %}
                            {% if label.labels is not null %}
                                <span>{{ label.labels.label.name }}</span>
                            {% endif %}
                            {% if label.defaultLabels is not null %}
                                <span>{{ label.defaultLabels.label.name }}</span>
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
{% endif %}
{% endblock %}